api/models.py
from flask import jsonify

from api import db
from sqlalchemy import func
from sqlalchemy.exc import SQLAlchemyError


class JobOffer(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    contact_name = db.Column(db.String(255))
    full_address = db.Column(db.String(255))
    city = db.Column(db.String(50))
    zip_code = db.Column(db.String(5))
    application_url = db.Column(db.String(500))
    company_name = db.Column(db.String(255))
    company_description = db.Column(db.Text())
    description = db.Column(db.Text())
    creation_date = db.Column(db.DateTime(timezone=True), default=func.now())
    contract_type = db.Column(db.String(50))
    contract_description = db.Column(db.String(255))
    duration = db.Column(db.String(100))
    id_pe = db.Column(db.String(100))

    def __init__(self, title, contact_name, full_address, city, zip_code, application_url,
                 company_name, company_description, description, creation_date, contract_type, contract_description,
                 duration, id_pe):
        self.title = title
        self.contact_name = contact_name
        self.full_address = full_address
        self.city = city
        self.zip_code = zip_code
        self.application_url = application_url
        self.company_name = company_name
        self.company_description = company_description
        self.description = description
        self.creation_date = creation_date
        self.contract_type = contract_type
        self.contract_description = contract_description
        self.duration = duration
        self.id_pe = id_pe

    @classmethod
    def get_all_job_offers(cls):

        # Retrieves all offers from DB

        try:
            job_offers = JobOffer.query.all()
            return job_offers
        except SQLAlchemyError as e:
            print(f"Error retrieving job offer: {str(e)}")

    @classmethod
    def insert_job_offer(cls, job_offer):

        # Inserts job offers into DB

        try:

            # Check if a job offer with the same id_pe already exists in the database
            existing_job_offer = JobOffer.query.filter_by(id_pe=job_offer.id_pe).first()

            if existing_job_offer:
                print("Job offer already exists in the database")
            else:
                db.session.add(job_offer)
                db.session.commit()
                print("Job offer added!")

        except SQLAlchemyError as e:
            db.session.rollback()
            print(f"Error inserting job offer: {str(e)}")

api/__init__.py
from os import path
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
DB_NAME = "diplodocus.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'Diplodocus'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views

    app.register_blueprint(views, url_prefix='/')

    from api.models import JobOffer

    with app.app_context():
        create_database(app)

    return app


def create_database(app):
    if not path.exists('api/' + DB_NAME):
        db.create_all()
        print('Database created!')

api/views.py
from flask import Blueprint, render_template, redirect
from api.services import JobOfferService, APICallService

views = Blueprint('views', __name__)


@views.route('/', methods=['GET'])
def index():
    job_offers = JobOfferService.get_all_job_offers_from_db()
    return render_template("home.html", job_offers=job_offers)


@views.route('/refresh', methods=['GET'])
def refresh_offers():
    APICallService.get_API_job_offers()
    return redirect('/')

api/templates/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id="home" href="{{ url_for('views.index') }}">Home</a>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

api/templates/home.html
{% extends "base.html" %} {% block title %} Home {% endblock %}
{% block content %}
    <br>
    <h1>Vos offres d'alternance</h1>
    <a class="btn btn-secondary" href="{{ url_for('views.refresh_offers') }}">Rafraîchir</a>
    <ul class="list-group list-group-flush" id="job_offers">
        {% for job_offer in job_offers %}
            <li class="list-group-item">
                <div class="text-primary"><strong>{{ job_offer.title }}</strong></div><br>
                <div class="text-dark">Entreprise : {{ job_offer.company_name }}</div>
                <div class="text-dark">Ville : {{ job_offer.city }}</div>
                <div class="text-dark">Durée : {{ job_offer.duration }}</div>
                <div class="text-dark">Type de Contrat : {{ job_offer.contract_type}}</div><br>
                <div class="text-dark">Description : </div><br>
                <div>{{ job_offer.description }}</div><br>
                <a class="btn btn-primary" href="{{ job_offer.application_url }}">Postuler</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}